"""One-time generator for the first-turn generalization set. Run once, review, then freeze.

The set must not come from the same assumptions as the agent's code, so it is
generated by a different model (Opus; the agent runs on Sonnet) with
instructions not to target the five supported categories. Regenerating it
changes the benchmark, so the output is committed and reused unchanged.

    cd backend && uv run python ../scripts/generate_generalization_set.py --out ../data/evaluation/generalization_openings.raw.json
"""

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "backend"))

from pydantic import BaseModel  # noqa: E402

from app.config import settings  # noqa: E402,F401  (loads .env)

GENERATOR_MODEL = "claude-opus-5-5"

PROMPT = """Write 110 realistic first messages that homeowners or renters might type into a chat assistant on a
home-services website when something is wrong at home. They live in Santa Clara / Sunnyvale / San Jose, California.

Do not optimize for any particular system or category list. Write the way real people write: often they don't know
what kind of professional they need, they describe symptoms rather than causes, and some problems don't need a
contractor at all (a utility outage, a tripped breaker, a landlord's responsibility, an appliance).

Cover all of these, with variety in each:
- clear symptoms; ambiguous symptoms; wrong self-diagnosis ("I think it's the pipes" when it's likely the roof)
- possible utility outages (water, power), including hints about whether neighbors are affected
- possible safety hazards (gas smell, burning smell, sparks, water near electrical, sewage, CO alarm)
- services a plumber/roofer/HVAC/electrician/water-restoration company would NOT do (pests, garage doors, locks,
  appliances, landscaping, internet, cleaning)
- very short inputs; colloquial language and slang; typos; no punctuation; ALL CAPS frustration
- multiple symptoms in one message; emotional or irrelevant detail; tenants mentioning a landlord
- people who include their ZIP or neighborhood, and people who don't
- a few that are not about a home problem at all

Each message is the user's FIRST message only (no assistant context). 1-3 sentences, mostly short.
For each, add 1-3 tags from: clear, ambiguous, wrong_diagnosis, utility, safety, out_of_scope, short, colloquial,
typos, multi_symptom, emotional, tenant, has_location, not_home_problem."""


class Opening(BaseModel):
    text: str
    tags: list[str]


class OpeningSet(BaseModel):
    openings: list[Opening]


def main() -> None:
    import anthropic

    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True)
    args = ap.parse_args()

    client = anthropic.Anthropic()
    with client.messages.stream(
        model=GENERATOR_MODEL,
        max_tokens=32000,
        output_config={"effort": "medium", "format": {"type": "json_schema", "schema": _schema()}},
        messages=[{"role": "user", "content": PROMPT}],
    ) as stream:
        message = stream.get_final_message()
    text = next(b.text for b in message.content if b.type == "text")
    data = OpeningSet.model_validate_json(text)
    Path(args.out).write_text(json.dumps([o.model_dump() for o in data.openings], indent=1, ensure_ascii=False) + "\n")
    print(f"wrote {len(data.openings)} openings to {args.out}; usage: {message.usage}")


def _schema() -> dict:
    from anthropic.lib._parse._transform import transform_schema

    return transform_schema(OpeningSet)


if __name__ == "__main__":
    main()
